//Search mode
export const SET_PLACEHOLDER = 'SET_PLACEHOLDER'
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER'
export const SEARCH_NOTE = 'SEARCH_NOTE'
export const ACTIVATE_SEARCH_INPUT = 'ACTIVATE_SEARCH_INPUT'
export const DEACTIVATE_SEARCH_INPUT = 'DEACTIVATE_SEARCH_INPUT'

//Notatka
export const ACTIVE_NOTE = 'ACTIVE_NOTE'
export const DEACTIVE_NOTE = 'DEACTIVE_NOTE'
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

//Notatka input
export const REQUEST_ADD_NOTICE_START = 'REQUEST_ADD_NOTICE_START'
export const FETCH_NOTES_REQUEST_DONE = 'FETCH_NOTES_REQUEST_DONE'
export const ZMIEN_TEKST = 'ZMIEN_TEKST'
export const ROZWIN_NOTKE = 'ROZWIN_NOTKE'
export const ZWIN_NOTKE = 'ZWIN_NOTKE'

//NotesList
export const FETCH_NOTES_REQUEST_START = 'FETCH_NOTES_REQUEST_START'
export const SET_SIZE = 'SET_SIZE'
export const SET_NOTES_POS = 'SET_NOTES_POS'

//Sidebar
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'





