//Search mode
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER'
//Input
export const SET_INPUT_ACTIVE = 'SET_INPUT_ACTIVE'
export const SET_INPUT_DEACTIVE = 'SET_INPUT_DEACTIVE'
export const SEARCH_NOTE_START = 'SEARCH_NOTE_START'
export const SEARCH_NOTE = 'SEARCH_NOTE'
export const SET_PLACEHOLDER = 'SET_PLACEHOLDER'

//Notatka
export const ACTIVE_NOTE = 'ACTIVE_NOTE'
export const DEACTIVE_NOTE = 'DEACTIVE_NOTE'
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

//Notatka input
export const REQUEST_ADD_NOTICE_START = 'REQUEST_ADD_NOTICE_START'
export const REQUEST_ADD_NOTICE_DONE = 'REQUEST_ADD_NOTICE_DONE'
export const REQUEST_ADD_NOTICE_REJECTED = 'REQUEST_ADD_NOTICE_REJECTED'
export const REQUEST_ADD_NOTICE_CANCELED = 'REQUEST_ADD_NOTICE_CANCELED'
export const ZMIEN_TEKST = 'ZMIEN_TEKST'
export const ROZWIN_NOTKE = 'ROZWIN_NOTKE'
export const ZWIN_NOTKE = 'ZWIN_NOTKE'

//NotesList
export const FETCH_NOTES_REQUEST_START = 'FETCH_NOTES_REQUEST_START'
export const FETCH_NOTES_REQUEST_DONE = 'FETCH_NOTES_REQUEST_DONE'
export const SET_SIZE = 'SET_SIZE'
export const SET_NOTES_POS = 'SET_NOTES_POS'

//Sidebar
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'





